# Generated by Django 3.1 on 2020-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dependants', models.IntegerField()),
                ('applicantincome', models.IntegerField()),
                ('coapplicantincome', models.IntegerField()),
                ('loanamt', models.IntegerField()),
                ('loanterm', models.IntegerField()),
                ('credithistory', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=15)),
                ('married', models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], max_length=15)),
                ('graduatededucation', models.CharField(choices=[('GRADUATE', 'GRADUATE'), ('NOT_GRADUATE', 'NOT_GRADUATE')], max_length=15)),
                ('selfemployed', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=15)),
                ('area', models.CharField(choices=[('RURAL', 'RURAL'), ('SEMIURBAN', 'SEMIURBAN'), ('URBAN', 'URBAN')], max_length=15)),
            ],
        ),
    ]
